# Generated by Django 4.0.6 on 2022-07-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('preview', models.ImageField(upload_to='')),
                ('announcement', models.BooleanField(default=False)),
            ],
        ),
    ]
