# Generated by Django 4.0.6 on 2022-07-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='preview',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
