# Generated by Django 4.0.6 on 2022-07-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.JSONField()),
                ('titles', models.JSONField()),
                ('plains', models.JSONField()),
                ('images', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/blog')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='spoiler',
            field=models.CharField(default='Text', max_length=255),
            preserve_default=False,
        ),
    ]
