# Generated by Django 4.0.6 on 2022-07-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_content_contentimage_event_spoiler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='images',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='content',
            name='plains',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='content',
            name='sequence',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='content',
            name='titles',
            field=models.JSONField(default=list),
        ),
    ]
