# Generated by Django 4.0.6 on 2022-07-25 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_content_images_alter_content_plains_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.content'),
        ),
        migrations.AlterField(
            model_name='event',
            name='preview',
            field=models.ImageField(upload_to='static/blog'),
        ),
    ]
