# Generated by Django 4.0.6 on 2022-07-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_content_alter_event_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_cover',
            field=models.BooleanField(default=True),
        ),
    ]
