# Generated by Django 4.0.6 on 2022-09-02 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_spoiler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('preview', models.ImageField(upload_to='static/blog')),
                ('spoiler', models.CharField(max_length=500)),
                ('announcement', models.BooleanField(default=False)),
                ('image_cover', models.BooleanField(default=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.content')),
            ],
        ),
    ]
